language: java
jdk: oraclejdk8

before_deploy:
    # Set up git user name and tag this commit
    - git config --local user.name "linosteiner"
    - git config --local user.email "linosteiner@gmail.com"
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag $TRAVIS_TAG


deploy:
  provider: releases
  api_key:
    secure: $GH_TOKEN
  file: out/artifacts/BattleshipFX/BattleshipFX.jar
  on:
    repo: https://github.com/linosteiner/BattleshipFX
    all_branches: true
    tags: true
  overwrite: true

cache:
  directories:
    - $HOME/.m2g