language: java
jdk: oraclejdk8

before_script:
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;


deploy:
  when: manual
  provider: releases
  api_key: $GH_TOKEN
  file: target/battleship.jar
  skip_cleanup: true
  on:
    tags: true

cache:
  directories:
    - $HOME/.m2g