language: java
jdk: oraclejdk8

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: target/battleshipfx.jar
  skip_cleanup: true
  on:
    tags: true

cache:
  directories:
    - $HOME/.m2g