language: java
jdk: oraclejdk8
before_deploy:
- git config --local user.name "linosteiner"
- git config --local user.email "linosteiner@gmail.com"
- export TRAVIS_TAG=${TRAVIS_BUILD_NUMBER}
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: WxQ24Bp89tSYSTVmCiXDTH+75P66Ogk3H5++mnguwzc2w4nXKJzNwBKEgMorFC8wNNrc5BL0zd7pO29O/6oD40kxzUGWf1Ot+wgdPVdJBM6DfnFAcqTMBWSoJ0iTnbiVJSs0mgLZgg+odniB2T0lRyKOd2AoHKJwR2fV0icdMIVfdHGLBJ7pGmakrjDUAqTagkqAa4yKf5EuET1eaoykoVvNvwRam7RthSZAC31N1GGfhPmoBc+X32sX8zR2clRPbVqoieKvN2eYkCIDTc88wc9IIsx0NzAy/TmTvdbSJf9lowJG3qrtsFq52pB6MKA0ZjGoZhais0J+EaVO+SPtS3BzDMT0qEFhHKQHz6Mc1UUpbZiyny6udo3HVwI2xFdUbspE9RxmrfuHRyQd2QwXfLfxQS9xJAt/XDY3Y7kt2FbYnVJbsVa9yzEh9XnBhRwrdPbnk6Sa3Rn1X9MuJZvqPDge9dB5zMm1fquaJfcR830QvRBw1h7CscyFtkaxF3sQiH6OHr9vgdk9D3R2tovOLF4skk7tw9fDtaFeRMAxNq54ZaubOcwi+Yxi1RV+dmp3rZpmKpH5xs9r9eWpobq5hkvvDV7yZ+lfRtcDIN0sJdpmsehEsxrX0NndqzG0z86U3T5dyCvY5T4fV/HXUfWEdN0uqfeE4XjsKfRgDCp80h0=
  file: out/artifacts/BattleshipFX/BattleshipFX.jar
  on:
    all_branches: true
    repo: linosteiner/BattleshipFX
  addons:
    artifacts: true
cache:
  directories:
  - "$HOME/.m2g"
